version: "3.6"
services: 
  
  zoneminder:
    container_name: zoneminder
    restart: always
    shm_size: 4096m
    environment:
      - TZ=Europe/London
      - ZM_DB_HOST=zm_db
    network_mode: znet
    ports:
      - 9080:80
    image: quantumobject/docker-zoneminder
